version: '3.8'

services:
#  server:
#    image: nginx:latest
#    ports:
#      - ${SERVER_PORT:-80}:80
#    volumes:
#      - ./:/var/www/html
#      - ./docker/server/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    ports:
        - ${SERVER_PORT:-80}:80
    command: php -S 0.0.0.0:80 -t /var/www/html/public
    depends_on:
        - db

  db:
    image: mariadb:10
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${DB_DATABASE:-database}
      MARIADB_USER: ${DB_USERNAME:-user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
        - db-data:/var/lib/mysql
  vite:
    image: node:20-alpine
    volumes:
        - .:/app
    working_dir: /app
    ports:
        - "${VITE_SERVER_PORT:-3000}:3000"
    command: npm run dev

volumes:
    db-data:
